#
# Copyright (C) 2023 Intel Corporation.
#
# SPDX-License-Identifier: BSD-3-Clause
#

FROM intel/dlstreamer:2024.1.1-dev-ubuntu22

USER root 

COPY ./requirements.txt /requirements.txt
RUN pip3 install --proxy $HTTP_PROXY --proxy $HTTPS_PROXY --upgrade pip --no-cache-dir -r /requirements.txt
