# INTEL CONFIDENTIAL
#
# Copyright (C) 2022 Intel Corporation
#
# This software and the related documents are Intel copyrighted materials, and your use of them is governed by the express
# license under which they were provided to you ("License"). Unless the License provides otherwise, you may not use, modify,
# copy, publish, distribute, disclose or transmit this software or the related documents without Intel's prior written permission.
#
# This software and the related documents are provided as is, with no express or implied warranties, other than those that are expressly stated in the License.

version: '3.4'
services:
  pipeline-server:
    build: .   
    ports:
      - 9554:9554
      - 8080:8080
    devices:      
      - /dev/video0:/dev/video0
    # network_mode: host
    volumes:
      - ./pipeline-server/models/2022:/home/pipeline-server/models
      - ./pipeline-server/pipelines:/home/pipeline-server/pipelines
      - ./pipeline-server/extensions:/home/pipeline-server/extensions
      - ./pipeline-server/results:/tmp/results
    environment:
      - cl_cache_dir=/home/pipeline-server/.cl-cache
      - LOG_LEVEL=INFO
      - GST_DEBUG=0
      - ENABLE_RTSP=true
      - RTSP_PORT=9554         
  pipeline-server2:
    build: .  
    ports:
      - 9555:9554
      - 8081:8080
    devices:      
       - /dev/video0:/dev/video0
    # network_mode: host
    volumes:
      - ./pipeline-server/models/2022:/home/pipeline-server/models
      - ./pipeline-server/pipelines:/home/pipeline-server/pipelines
      - ./pipeline-server/extensions:/home/pipeline-server/extensions
      - ./pipeline-server/results:/tmp/results
    environment:
      - cl_cache_dir=/home/pipeline-server/.cl-cache
      - LOG_LEVEL=INFO
      - GST_DEBUG=0
      - ENABLE_RTSP=true
      - RTSP_PORT=9554   
  pipeline-server3:
    build: .   
    ports:
      - 9556:9554
      - 8082:8080
    devices:      
       - /dev/video0:/dev/video0
    # network_mode: host
    volumes:
      - ./pipeline-server/models/2022:/home/pipeline-server/models
      - ./pipeline-server/pipelines:/home/pipeline-server/pipelines
      - ./pipeline-server/extensions:/home/pipeline-server/extensions
      - ./pipeline-server/results:/tmp/results
    environment:
      - cl_cache_dir=/home/pipeline-server/.cl-cache
      - LOG_LEVEL=INFO
      - GST_DEBUG=0
      - ENABLE_RTSP=true
      - RTSP_PORT=9554   
  pipeline-server4:
    build: .   
    ports:
      - 9557:9554
      - 8083:8080
    devices:      
       - /dev/video0:/dev/video0
    # network_mode: host
    volumes:
      - ./pipeline-server/models/2022:/home/pipeline-server/models
      - ./pipeline-server/pipelines:/home/pipeline-server/pipelines
      - ./pipeline-server/extensions:/home/pipeline-server/extensions
      - ./pipeline-server/results:/tmp/results
    environment:
      - cl_cache_dir=/home/pipeline-server/.cl-cache
      - LOG_LEVEL=INFO
      - GST_DEBUG=0
      - ENABLE_RTSP=true
      - RTSP_PORT=9554   
  pipeline-initiator:
    image: postman/newman    
    command: run /collections/VAS.postman_multiserver.json -e "/collections/VAS_Environment.postman_environment.json" --verbose
    volumes:
      - ./postman-rest/:/collections
