OvmsClient:
  PipelineScript: run_grpc_python.sh
  PipelineInputArgs: "--model_name instance-segmentation-security-1040" # space delimited like we run the script in command and take those input arguments
