apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose -f docker-compose.yml convert -o object-detection-service-low-code-3.1.0 -c
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: camera-simulator
  name: camera-simulator
spec:
  ports:
    - name: "8554"
      port: 8554
      targetPort: 8554
  selector:
    io.kompose.service: camera-simulator
status:
  loadBalancer: {}
