apiVersion: v1
kind: PersistentVolume
metadata:
  name: dlstreamer-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 150Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/home/intel/projects/intel-retail/automated-self-checkout/results"