name: Build docker images

on: workflow_dispatch

permissions:
  contents: read

jobs:
  build_DLStreamer:
      runs-on: ubuntu-latest
      steps:
          - name: Checkout code
            uses: actions/checkout@v3
          - name: Make dgpu Docker images
            run: |
              make build-dlstreamer
  build_OVMS_Client:
      runs-on: ubuntu-latest
      steps:
          - name: Checkout code
            uses: actions/checkout@v3
          - name: Build ovms client
            run: |
              make build-ovms-client
